### PR TITLE
support baseURL in profile

### PR DESCRIPTION
**Pull request by ianhe8x**
this way we can setup other env in credentials and use -p to switch
```
[local]
onf_access_key    = ...
onf_secret_key    = ...
default_workspace = ...
base_url          = http://localhost:5000/api/v1
```

### CODE REVIEW

**Comment by zhex** [comment]
baseUrl rewrite already exists in the current version. it should be rear used by the end-user, only for developers like us, so we don't want it to be in the credential file.

you can create a debug file under `~/.onf` folder, the content looks like this:


```
{
 "baseurl": "https://api.onfinality.me/api/v1"
}
```

**Comment by ianhe8x** [comment]
I saw it, but it's not convenient, the overwrite apply to all profiles. With this PR, I can add profiles for each env like local, dev and they can have their own baseUrl

**Comment by ianhe8x** [comment]
Since we already support usage of profile, this will be useful. I can't think of other scenario why people will use profile if not have a different baseurl

**Comment by ianhe8x** [comment]
oh I forget, they can create profile for different workspaces. but it doesn't mean profile for environment isn't useful.

**Comment by zhex** [comment]
yes, we thought this before. but for the end-user, only one env: our production. multiple envs are only for the developers. our original goal is the baseUrl change should never in the credential file. so we create a separate file for our internal use only, the end-user should never need to create it.

so for your requirement, I think we'd better to enhance the debug file to support multiple profiles we defined in the credential file

**Comment by ianhe8x** [comment]
how about this, I won't add baseUrl in profile, but instead add an optional flag `--base-url`

**Comment by zhex** [comment]
this is also an option we had before, but if we add a new flag, it will also show it in the help, we don't want to list this to the end-user and explain what it is for.

**Comment by ianhe8x** [comment]
then read it from environment

**Comment by zhex** [comment]
Yes, env is a possible option, but I don't see much difference from the current solution.

**Comment by ianhe8x** [comment]
I can assign it differently per execution, which save a lot of time

**Comment by zhex** [comment]
yes, this is a reasonable case. we can have an ENV something like ONF_BASE_URL.

**Pull request merged**
